image: ${DEFAULT_REPO}/entdecken/docker-dind-sbt

stages:
  - build
  - publish

variables:
  APP_NAME: kafka-connect-field-and-time-partitioner
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  tags: ['kmo-aws-entdecken']
  artifacts:
    paths:
    - target/*.jar
  before_script:
  - aws-docker-authenticate
  script:
  - mvn clean test package

publish:
  stage: publish
  only: ['master']
  dependencies:
  - build
  before_script:
  - aws-docker-authenticate
  script:
  - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
